name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cargo check
      run: cargo check --verbose
    - name: Yarn build for test
      run: |
        yarn global add @vue/cli
        yarn --cwd ./vue build
    - name: Run tests
      run: GECKOWEBDRIVER & cargo test -- --test-threads=1
