name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Yarn build for test
      run: |
        yarn add @vue/cli-service
        yarn --cwd ./vue ./node_modules/.bin/vue-cli-service build
    - name: Cargo check
      run: cargo check --verbose
    - name: Run tests
      run: GECKOWEBDRIVER & cargo test -- --test-threads=1
