services:
  db-test:
    image: postgres
    ports:
      - "6543:5432"
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: postgres

  selenium:
    image: selenium/standalone-chromium:136.0
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SE_NODE_MAX_SESSIONS: 50
